version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=ws://localhost:8080

  backend:
    build:
      context: ./server/Tetrispp
      dockerfile: ./Tetrispp/Dockerfile
    ports:
      - "8080:8080"
