---
- hosts: all
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes
    - name: Ensure /etc/apt/keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: Add Docker GPG key if not already added
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
      register: docker_gpg_key
    - name: Determine correct architecture for Docker
      set_fact:
        docker_arch: >-
          {% if ansible_architecture == "x86_64" %}amd64
          {% elif ansible_architecture == "aarch64" %}arm64
          {% elif ansible_architecture == "armv7l" %}armhf
          {% else %}{{ ansible_architecture }}{% endif %}
    - name: Set up Docker repository
      template:
        src: docker.list.j2
        dest: /etc/apt/sources.list.d/docker.list
        mode: '0644'
    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes
    - name: Ensure Docker service is running and enabled
      service:
        name: docker
        state: started
        enabled: yes
